<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="addCompany.aspx.cs" Inherits="Medical.addCompany" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
      <style type="text/css">         .auto-style12 {             width: 122px;             font-weight: bold;             color: #fff;         }         .auto-style13 {             width: 355px;         }     </style> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link href="addcompany.css" rel="stylesheet" /> 
 
    <div class="tab1">         <h2>Add Company</h2>     <table>         <tr>             <td class="auto-style12">Company Name </td>             <td class="auto-style13">                 <asp:TextBox ID="TextBox1" runat="server" CssClass="t1" placeholder="Add company name"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="textbox1" Text="must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>         </tr>         <tr>             <td class="auto-style12">Adress</td>             <td class="auto-style13">                 <asp:TextBox ID="TextBox2" runat="server" CssClass="t2" placeholder="Enter adress"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="textbox2" Text="must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>         </tr>         <tr>             <td class="auto-style12">Contact Person</td>             <td class="auto-style13">                 <asp:TextBox ID="TextBox3" runat="server" CssClass="t3" placeholder="enter person info"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="textbox3" Text="must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>         </tr>         <tr>             <td class="auto-style12">Mobile Number</td>             <td class="auto-style13">                 <asp:TextBox ID="TextBox4" runat="server" CssClass="t4" placeholder="phone num" textmode="Number"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="textbox4" Text="must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>         </tr>         <tr>             <td class="auto-style12">&nbsp;</td>             <td class="auto-style13">                 <asp:Button ID="Button1" runat="server" CssClass="b1" Text="Add Company" Width="120px" />             </td>         </tr>     </table>     </div> 
</asp:Content>
