<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ChangePassword.aspx.cs" Inherits="Medical.ChangePassword" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style type="text/css">         .auto-style12 {             font-weight: bold;             color: #fff;             width: 142px;         }         .auto-style13 {             font-weight: bold;             color: #fff;             width: 120px;         }         .auto-style14 {             color: white;             outline-width: medium;             outline-style: none;             outline-color: invert; font-size: 16px;             border-left-style: none;             border-left-color: inherit;             border-left-width: medium;             border-right-style: none;             border-right-color: inherit;             border-right-width: medium;             border-top-style: none;             border-top-color: inherit;             border-top-width: medium;             border-bottom: 3px solid #fff;             margin-bottom: 20px;             background-color: transparent;         }     </style> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <link href="changepassword.css" rel="stylesheet" /> 
 
    <div class="tab1"> <h2>Change Password</h2>     <table class="auto-style10">         <tr>             <td class="auto-style13">Old Password</td>             <td class="auto-style12">                 <asp:TextBox ID="TextBox1" runat="server" CssClass="t1" Width="158px" Height="39px" placeholder="Enter Old Password" TextMode="Password"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="textbox1" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>             </tr>         <tr>              <td class="auto-style13">New Password</td>             <td class="auto-style12">                 <asp:TextBox ID="TextBox2" runat="server" CssClass="t2" Width="184px" placeholder="Enter New Paaword" TextMode="Password"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="textbox2" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>           </tr>         <tr>                  <td class="auto-style13">Confirm Password</td>             <td class="auto-style12">                 <asp:TextBox ID="TextBox3" runat="server" CssClass="auto-style14" Width="231px" Height="40px" placeholder="Re-enter Password" TextMode="Password"></asp:TextBox>                 <asp:CompareValidator ID="CompareValidator1" runat="server" ErrorMessage="2 fields must match" ControlToValidate="textbox3" ValueToCompare="textbox2"></asp:CompareValidator>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="textbox3" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>                      </tr>      <tr>             <td class="auto-style13">             </td> <td class="auto-style12">                 <asp:Button ID="Button1" runat="server" CssClass="b2" Text="Save Password" Width="207px" />             </td>             </tr>            </table> </div>
</asp:Content>
