<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Reports.aspx.cs" Inherits="Medical.Reports" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
            <style type="text/css">         .auto-style11 {             width: 275px;         }         .auto-style12 {             width: 252px;         }         .auto-style13 {             height: 228px;             width: 998px;         }         .auto-style15 {         width: 275px;         font-style: italic;         font-weight: bold;         font-size: x-large;         color: #FF0000;     }     .auto-style16 {         width: 252px;         font-style: italic;         font-weight: bold;         font-size: x-large;         color: #FF0000;     }     .auto-style17 {         font-size: x-large;         color: #FF0000;         font-style: italic;   font-weight: bold;     }     </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link href="PIC.css" rel="stylesheet" />     <table class="auto-style13">         <tr>             <td class="auto-style11">                 <asp:ImageButton ID="ImageButton1" runat="server" Height="124px" ImageUrl="1.jpg"  Width="258px" CssClass="p1" OnClick="ImageButton1_Click1"/>             </td>             <td class="auto-style12">                 <asp:ImageButton ID="ImageButton2" runat="server" Height="117px" ImageUrl="2.jpg" Width="238px" CssClass="p2" OnClick="ImageButton2_Click1"/>             </td>             <td>                 <asp:ImageButton ID="ImageButton3" runat="server" Height="121px" ImageUrl="3.jpg" Width="250px" CssClass="p3" OnClick="ImageButton3_Click1"/>             </td>         </tr>          <tr>             <td class="auto-style15">                 User&nbsp;Report</td>             <td class="auto-style16">                 Company Report</td>             <td class="auto-style17">                 ClientReport</td>         </tr>     </table> 

</asp:Content>
