<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="updateStock.aspx.cs" Inherits="Medical.updateStock" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style type="text/css">         .auto-style10 {             width: 64%;         }         .auto-style11 {             width: 471px;             font-weight: bold;             color: #fff;         }         .auto-style12 {             width: 237px;         }         .auto-style13 {             color: white;             outline-width: medium;             outline-style: none;             outline-color: invert;             font-size: 16px;             border-left-style: none;             border-left-color: inherit;             border-left-width: medium;             border-right-style: none;             border-right-color: inherit;             border-right-width: medium;             border-top-style: none;             border-top-color: inherit;             border-top-width: medium;             border-bottom: 3px solid #fff;             margin-left: 24px;  margin-bottom: 20px;             background-color: transparent;         }         .auto-style14 {             color: white;             outline-width: medium;             outline-style: none;             outline-color: invert;             font-size: 16px;             border-left-style: none;             border-left-color: inherit;             border-left-width: medium;             border-right-style: none;             border-right-color: inherit;             border-right-width: medium;             border-top-style: none;             border-top-color: inherit;             border-top-width: medium;             border-bottom: 3px solid #fff;             margin-left: 14px;             margin-bottom: 20px;             background-color: transparent;         }         .auto-style15 {             width: 100%;             color: white;             outline-width: medium;             outline-style: none;             outline-color: invert;             height: 40px;             font-size: 16px;             border-left-style: none;             border-left-color: inherit;             border-left-width: medium;             border-right-style: none;             border-right-color: inherit;             border-right-width: medium;             border-top-style: none;             border-top-color: inherit;             border-top-width: medium;             border-bottom: 3px solid #fff;             margin-left: 11px;             margin-bottom: 20px;             background-color: transparent;         }     </style> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <link href="UpdateStock.css" rel="stylesheet" /> 
 
    <div class="tab1"> <h2>Update Stocks</h2>     <table class="auto-style10">         <tr>             <td class="l1">Item Name</td>             <td class="auto-style12">   <asp:TextBox ID="TextBox1" runat="server" CssClass="auto-style13" Width="158px" Height="39px" placeholder="Enter Item Name"> </asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"   ControlToValidate="textbox1" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>             <td>                 <asp:Button ID="Button1" runat="server" Text="Select" Width="127px" CssClass="b1" />             </td></tr>         <tr>              <td class="l2">Current Quantity</td>             <td class="auto-style12">                 <asp:TextBox ID="TextBox2" runat="server" CssClass="auto-style15" Width="184px" placeholder="Enter Current Quantity"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server"   ControlToValidate="textbox2" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>           </tr>         <tr>                  <td class="l3">Quantity</td>             <td class="auto-style12">                 <asp:TextBox ID="TextBox3" runat="server" CssClass="auto-style14" Width="192px" Height="40px" placeholder="Enter Quantity"></asp:TextBox>                 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server"   ControlToValidate="textbox3" Text="Must be filed" ForeColor="Red"></asp:RequiredFieldValidator>             </td>             <td>         </tr>         <tr>                  <td class="auto-style11">&nbsp;</td>             <td class="auto-style12">                 <asp:Button ID="Button2" runat="server" CssClass="b2" Text="Update" Width="207px" />             </td>             <td>                 &nbsp;</tr>     </table>         </div> 
</asp:Content>
